name: "Synthia"
version: "1.0.0"
slug: "synthia"
description: "Your personal AI assistant for email summaries and more."
arch:
  - amd64
  - armv7
  - armhf
init: false
options:
  gmail_api_key: ""
  openai_api_key: ""
  notify_service: "notify.mobile_app_your_phone"
schema:
  gmail_api_key: str
  openai_api_key: str
  notify_service: str
